
name: "Release package"
on: 
  push:
    branches:
      - master
      - main

jobs:
  release_package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "npm install"
        run: npm ci

      - name: "npm semantic-release"
        run: npm semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
